### ISSUE TITLE
Add fte_total_census to utDataStoR

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utDataStoR#15]
Add fte_total_census to utDataStoR to replace
fte_gr_cred_hour_census and fte_ug_cred_hour_census
have the new query report both ug, gr, and total fte by term and do it in only one query instead of two.

When reporting FTE it is often reported in 3 ways, undergraduate fte, graduate fte and total fte. Writing 1 query for all 3 of these requests makes the most sense and means that there are less queries to manage in utDataStoR.

**Comment by andreabr-dixie** [comment]
I checked the sql that I plan to use and it matches the ushe census report for spring. It matches at the total, the undergraduate and graduate level.

**Comment by andreabringhurst** [comment]
This issue will be done as soon as the #22 Pull request is approved.
