### ISSUE TITLE
Add fte_total_eot.sql to utDataStoR

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utDataStoR#16]
Add fte_total_eot to utDataStoR to replace
 fte_ug_cred_hour_eot
have the new query report both ug, gr, and total fte by term and do it in only one query so that we don't need to create additional queries for gr and total.

When reporting FTE it is often reported in 3 ways, undergraduate fte, graduate fte and total fte. Writing 1 query for all 3 of these requests makes the most sense and means that there are less queries to manage in utDataStoR.

**Comment by andreabr-dixie** [comment]
I checked the sql that I planed to use and it didn't match the ushe eot report for spring. @JoyBaule and I discussed using earned_credits for end of term; but that is wrong. Both census and end of term use attempted_credits.

**Comment by andreabringhurst** [comment]
This issue will be done as soon as the https://github.com/ut-effectiveness/utDataStoR/pull/22 Pull request is approved.
