### ISSUE TITLE
Concerns about fte_off_edify.sql

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utDataStoR#18]
After reviewing fte_off_edify.sql here are my concerns:
it is using student level instead of course level when calculating the fte
it is using registered_credits, and fte_grad_cred_hour_census, fte_ug_cred_hour_census, and fte_ug_cred_hour_eot are using attempted_credits

**Comment by andreabr-dixie** [comment]
I would like to delete this query and have this data come from a new query #17 fte_total_current.

**Comment by andreabringhurst** [comment]
This issue will be done as soon as the https://github.com/ut-effectiveness/utDataStoR/pull/22 Pull request is approved.
