### ISSUE TITLE
Finish outstanding vignettes

### ISSUE THREAD

**Issue by MattNickodemus** [ut-effectiveness/utDataStoR#24]
Let's get all the vignettes listed in this issue in utVignetteR
https://github.com/ut-effectiveness/utVignetteR/issues/6

**Comment by andreabr-dixie** [comment]
- utDataStoR - Joy
- [ ] Headcount - Pull request in utVignetteR https://github.com/ut-effectiveness/utVignetteR/pull/1
- [ ] Full_Time_Equivalent -Pull request in utVignetteR https://github.com/ut-effectiveness/utVignetteR/pull/7
- [ ] Retention - Pull request in utVignetteR https://github.com/ut-effectiveness/utVignetteR/pull/2
- [ ] Cohort - Pull request in utVignetteR https://github.com/ut-effectiveness/utVignetteR/pull/3
- [ ] 150_Percent_Graduation_Rate - Pull request in utVignetteR https://github.com/ut-effectiveness/utVignetteR/pull/4
- [ ] Groups - Pull request in utVignetteR https://github.com/ut-effectiveness/utVignetteR/pull/5

- utHelpR - Andrea
- [ ] Counting - styling

- utMetrics - Andrea
- [ ] utMetrics - styling
- [ ] naming_metrics - styling
- [ ] utmetrics_computations - styling

**Comment by MattNickodemus** [comment]
@andreabr-dixie Can we add a due date to this issue?

**Comment by andreabr-dixie** [comment]
@MattNickodemus I have added a due date of Sept. 27

**Comment by andreabr-dixie** [comment]
After reviewing the project in morning huddle, it was decided that all 4 pull request (#27 #25 #26 #28 ) would be reviewed today (9/30/24) and made available to Craig to build a bookdown tomorrow (10/01/24).

**Comment by andreabr-dixie** [comment]
@MattNickodemus @cdemkegit I think we can close this issue because the vignettes have been moved into Main and are published. Please comment if you agree or disagree.

**Comment by andreabringhurst** [comment]
@MattNickodemus @cdemkegit Closing this now that issue #36 is complete.
