### ISSUE TITLE
republish utDataStor pkgdown

### ISSUE THREAD

**Issue by cdemkegit** [ut-effectiveness/utDataStoR#29]
After all the pull request (pr) are merged. Republish the pkgdown with all the new and updated vignettes.
 
- [x] #25 
- [x] #27 
- [x] #26 
- [x] #28
- [x] make any changes like adding / documenting dependent packages used by the vignettes in the description file 
- [x] create a new pr to main
- [x] republish utDataStor pkgdown

**Comment by cdemkegit** [comment]
@andreabr-dixie I'm I missing anything?

**Comment by andreabr-dixie** [comment]
@cdemkegit  you are missing one more pull request #28 .
