### ISSUE TITLE
Make adjustments to utMetrics Computations vignette

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utDataStoR#36]
We should add a discussion of how this (150% Graduation Rate) impacts non bachelors students. We can catch that in the next round of reviews, but I think we'll need something.

**Comment by andreabr-dixie** [comment]
@MattNickodemus @cdemkegit I have reviewed this comment from Matt that I saved from a merge pull request. After reading it, I don't think that the utMetrics Computations vignette is the right place for it. I think it should go in the 150% graduation rate vignette. Is it okay if I make the addition/clarification in the 150% graduation rate vignette?

**Comment by andreabringhurst** [comment]
@MattNickodemus @cdemkegit I made changes to the 150% graduation rate vignette and had @JoyBaule review it. I am going to close this issue.
