### ISSUE TITLE
Create a Template for Vignettes

### ISSUE THREAD

**Issue by andreabr-dixie** [ut-effectiveness/utDataStoR#4]
Create a template for vignettes that incorporates consistent themes, fonts, and layouts for visual appeal. Enhance the aesthetics of the vignettes, including formatting, adding relevant visualizations, and ensuring style consistency. Incorporate Sesame Street images where appropriate.

Use the Headcount vignette to make the template:
https://github.com/ut-effectiveness/utDataStoR/blob/648f94ad1b5da92aba04f4329391573548451696/vignettes/headcount.Rmd#L2C1-L7C28

Use the Counting vignette to provide inspiration: 
https://github.com/ut-effectiveness/utHelpR/blob/e0e0244eb31543ec5503af0dc8dd88843ae8386d/vignettes/counting.Rmd#L2

**Comment by andreabr-dixie** [comment]
@JoyBaule @MattNickodemus based on our conversation today, what I heard is that Joy will add documentation about how to style a vignette to the readme file of utVignetteR.  Instead of a template, the information will be housed in the readme file. Am I correct?

**Comment by MattNickodemus** [comment]
@andreabr-dixie Yes. That's what I remember as well.

**Comment by MattNickodemus** [comment]
@andreabr-dixie Are you okay if we close this issue? I think we have everything we need.

**Comment by JoyBaule** [comment]
@andreabr-dixie, here is a link the Readme file for utVingetteR:

https://github.com/ut-effectiveness/utVignetteR/blob/main/README.md

This has the instructions for adding a YAML to each new vignette created.

**Comment by andreabr-dixie** [comment]
@MattNickodemus and @JoyBaule , yes, I we can close this issue now.
