### ISSUE TITLE
Review and Document SQL

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utDataStoR#7]
- Read through all the SQL code.
- Identify the purpose and functionality of each query.
- Note any immediate issues or areas for improvement.
- Create consistency in the queries in both structure and output.
- Add comments explaining the purpose of each query.
- Document any assumptions or dependencies.

**Comment by andreabr-dixie** [comment]
I have moved the due date to Oct. 11 to give me time to work on #10 Retention SQL.

**Comment by andreabringhurst** [comment]
This is getting moved to paused. The retention sql is ready, but it hasn't been through code review or the Technical subcommittee. This should be saved for the next milestone.

**Comment by andreabringhurst** [comment]
The remaining SQL that needs to be reviewed is the Validation folder of sql.
